### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by niikoolaa04** [bradenstrother/bCore#1]
Is redis Necessary if im gonna use 1 server?

**Comment by bradenstrother** [comment]
Yes, redis is necessary for my version of the core. It could be redone to work without redis, but it would be a lot of work for a slower, less secure, and less stable version.

**Comment by niikoolaa04** [comment]
You said for your version, there are another version?

**Comment by bradenstrother** [comment]
No, I mean if you were to modify it.

**Comment by niikoolaa04** [comment]
Okay, thanks for answer. Good bye
